### ISSUE TITLE
Error: session could not be loaded

### ISSUE THREAD

**Issue by gsnyder-flvc** [europeana/REPOX#28]
I'm brand new to Repox.  I've been following the steps in the 5 minute setup and think I've successfully gotten to the bottom of the list.  On the last step, open the URL in my browser, I receive the error: session could not be loaded.   I've looked in the Catalina log and in the MySQL log but I don't see what is causing the problem.  Is there a Repox error log somewhere I should check?

Thanks
--Gerald

**Comment by stzanakis** [comment]
Hi Gerald,

I suppose you are installing in linux?
What is the exact url you try to access?
What is the name of the war you try to deploy?

There is also the log file "${catalina.base}/logs/repox.log" for repox logs.

**Comment by gsnyder-flvc** [comment]
Sorry.  Yes, Linux, Tomcat, MySQL.    Thanks for mentioning the repox.log, I hadn't noticed that.  

The url is: http://testcat.fcla.edu/repox/.  We have other Tomcat apps running on this test server. 

The war file is: repox.war

I was having some trouble with slf4j-simple-1.6.3.jar.  I saw some warnings about slf4j defaulting to no log.   I think I have the simple jar file in place now.  I removed the /repox/data directory for a clean start.  The MySQL user doesn't show any tables created.  Sent the new war file to Tomcat.  

The messages in the catalina.out file look normal.  There are many INFO messages in the repox.log, with warnings about using default configuration.properties file.   

Back to the url, same message,  Error: session could not be loaded.  

I was watching the catalina.out log and the repox.log when I entered the url.  I did not see any new messages in the log files   My web browser displays an image: loading REPOX, so it seems I'm reaching the REPOX webapp.

Is there a more appropriate place for me to post these questions?   Thanks very much for your help.

--Gerald

**Comment by stzanakis** [comment]
Well I cannot say much from here, but does the MySQL user have permission to write on the schema?
Are the directories under the /repox/data created?
Also the directory /repox/data you provide for REPOX, does it have the correct permissions to write? Can you update the permission to full access to everyone and test if it works?

Can you also provide the logs of the repox.log and catalina.out?

Yes here is a good place! :) Except if you need to provide confidential information, then you can send me an email, and see if I can help further.

**Comment by gsnyder-flvc** [comment]
I think the MySQL user has proper permissions, but I'll double check that.  The tomcat user created  the data directory and several sub-directories so those permissions seem good.  I'll dig out some of the log extracts to send.   I'll put together more of the details to send next week.   

Thanks

**Comment by gsnyder-flvc** [comment]
Repox has been temporarily sidelined due to some other work.  We hope to get back to Repox fairly soon.  Thanks for your help last week.     --Gerald

**Comment by gsnyder-flvc** [comment]
Getting back to Repox now.   I tried to reset everything.  Pulled a new copy of REPOX, deleted the /repox/data  directory.  Double checked that the mysql user id could create a table.  The build looks okay.    I added slf4j-log4j12-1.6.3.jar file to the WEB_INF/lib directory.  

When I deploy the repox.war file to tomcat, the messages in the catalina.out file look okay.  Some messages go the repox log file.   

Using this url: http://testcat.fcla.edu/repox/ 

I see the loading repox image and get the message: Error: session could not be loaded. 

I've placed a few log files to review that may hopefully help.   I deploy the repox.war file, did not see any messages when I requested the repox url.  Then I requested an undeploy of repox, which started many messages in Tomcat.

http://testcat.fcla.edu/gsnyder/clean_install.log.20160801
http://testcat.fcla.edu/gsnyder/repox.log
http://testcat.fcla.edu/gsnyder/catalina.out

Any ideas would be appreciated.  
Thanks
--Gerald

**Comment by stzanakis** [comment]
Hello!

From what I see from repox.log it is going through looping the deployment for some reason.
Can you give me some more details?
What versions are you using so I can test it myself? tomcat, mysql, java
And how do you deploy? By copying the .war to the webapps directory and starting tomcat or from tomcat manager?

**Comment by stzanakis** [comment]
I just tested on the following configuration and it works:
Ubuntu 16.04
openjdk version "1.8.0_91"
tomcat 8.5.4
mysql 5.7.13

**Comment by gsnyder-flvc** [comment]
I had been using the Tomcat manager to deploy the war file.  I copied the war file to the webapps directory and restarted Tomcat.  It did not appear to change anything. 

Is there a log option to activate to get more messages about the session error?  I was having trouble with the slf4j log4j in the Maven project.  So I'm not sure if the logging is working properly.  

In looking at the html, it appears to be running this script:  harvesterui/vim haharvesterui.nocache.js.   Is this the initial code that should run?

Here are the versions:
Tomcat Version: Apache Tomcat/6.0.24	
JVM version: 1.7.0_80-b15	
JVM vendor: Oracle Corporation	
OS name: Linux	
OS version: 2.6.32-642.1.1.el6.x86_64
OS Architecture:	amd64

Thanks.  --Gerald

**Comment by stzanakis** [comment]
The logs look that they are generated fine since you get the repox.log file.
I just tested similar configuration as yours and it's working.

What I find strange from your "repox.log" is that the application is going through a loop of initializing itself.
On first start the logs should stop on the line "Generating Data Source counts".

As a next try I would remove all the jars from local maven repository and rebuild the project. Also try building it from another machine and deploy it on the server. Can you try that?

P.S. Unrelated to this problem I would recommend using PostgreSQL, there are more updates there that mysql.

**Comment by gsnyder-flvc** [comment]
I removed the .m2/repository directory and rebuilt the project.   I also copied the repox.war file directly to the webapps directory, which started the deploy.   I didn't seem to change anything.  The logs looked the same and I still get the same error.  

I think in on our Tomcat test site we have a few different virtual hosts defined and Tomcat may launch some multiple deploy activities for the multiple hosts.  I'm not completely sure what's going there.  

Our DBA person is going to create a database on PostgreSQL to test instead of MySQL.  He may also try an install on a different Linux server, so we might learn something new there.

Thanks again.

**Comment by stzanakis** [comment]
Ok Gerald,

Let me know of any news.

**Comment by gsnyder-flvc** [comment]
Our DBA, tried installing Repox on a different Linux server with PostgreSQL.  His version is working.   We're going to compare the two installations to try to understand where the problem is with the first try. 

Thanks for helping.  I'll let you know if we figure out what that snag is.
--Gerald

**Comment by gsnyder-flvc** [comment]
We found 2 conditions that were part of my trouble.  Apparently there's a MySQL setting to allow an external connection, that I was missing.  The 2nd problem has something to do with the project and the way it's deployed on Tomcat.  If I go directly to Tomcat:8080/repox,  Repox works.  If I use our virtual host name, testcat/repox, it does not work.  Not sure of the details, but at this point I don't need to know.

**Comment by stzanakis** [comment]
Hi Gerald,

I'm glad it's resolved for you. I didn't know about the virtual host thing since I have deployed repox before in cloud foundry environment and it was working.
Please close issue if it's working now.

Cheers,
Simon

**Comment by gsnyder-flvc** [comment]
Our test version of Repox is working.  We may still have a Tomcat configuration problem with the way the war file deploys but we will deal with that later.   

Thanks for your help.   --Gerald

**Comment by j4lib** [comment]
Just a hint as someone else might have a similar problem:
I had the same error message saying that the "session could not be loaded". In the logs there was a ClassCastException which lead me to the error. In my _default.email.pass_ in the config file, there was a comma that was not escaped.
